import Nav from "@/components/Nav";
import { ContextProvider } from "@/Providers/ContextProvider";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ContextProvider>
              <div className="container lg:max-w-[1000px] mx-auto">
                <Nav />
                {children}
              </div>
            </ContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
